# A short, descriptive name of this building block collection
name: OGC API Common

# Short abstract for this collection (optional)
abstract: |
  Building blocks for OGC API - Common.

# Description for this collection (optional)
description: |
  OGC API - Common is a multi-part standard that documents the set of common practices and 
  shared requirements that have emerged from the development of Resource Oriented Architectures 
  and Web APIs within the OGC. Standards developers will use these building-blocks in the 
  construction of other OGC Standards that relate to Web APIs. The result is a modular suite 
  of coherent API standards which can be adapted by a system designer for the unique requirements 
  of their system. As such, this OGC API Standard serves as the "OWS Common" standard for 
  resource-oriented OGC APIs. 
  
  Consistent with the architecture of the Web, this specification uses a resource architecture 
  that conforms to principles of Representational State Transfer (REST).
  
  This OGC API Standard establishes a common pattern that is based on OpenAPI. 

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.api.common.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# Whether to enable the (highly experimental) downcompiling of JSON schemas to an OpenAPI 3.0-compatible
# version
schema-oas30-downcompile: False

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
#   resources:                              # Additional resources to upload apart from building block metadata
#      ontologies: true                     #   Whether to upload ontology files to the triplestore